# INSTALLATION
# 1. Install Helm: https://helm.sh/docs/intro/install/
# 2. Add ingress-nginx help repo: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
# 3. Update information of available charts locally from chart repositories: helm repo update
# 4. Install ingress-nginx:
# helm upgrade --install \
# ingress-nginx ingress-nginx/ingress-nginx \
# -f ./ingress-nginx-annotations.yaml \
# --namespace ingress-nginx \
# --create-namespace

# LIST of all ANNOTATIONS: https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/master/internal/annotation/load_balancer.go

controller:
 kind: DaemonSet
 service:
  annotations:
   # Germany:
   # - nbg1 (Nuremberg)
   # - fsn1 (Falkensteing)
   # Finland:
   # - hel1 (Helsinki)
   # USA:
   # - ash (Ashburn, Virginia)
      # - hil (Hillsboro, Oregon)
   # Without this the load balancer won't be provisioned and will stay in "pending" state.
   # The state you can check via "kubectl get svc -n ingress-nginx"
   load-balancer.hetzner.cloud/location: $CLUSTER_LOCATION

   # Name of load balancer. This name you will see in your Hetzner's cloud console (site) at the "Your project -> Load Balancers" page
   load-balancer.hetzner.cloud/name: worker_LB

   # Ensures that the communication between the load balancer and the cluster nodes happens through the private network
   load-balancer.hetzner.cloud/use-private-ip: "true"

   # [ START: If you care about seeing the actual IP of the client then use these two annotations ]
   # - "uses-proxyprotocol" enables the proxy protocol on the load balancers so that ingress controller and
   # applications can "see" the real IP address of the client.
   # - "hostname" is needed just if you use cert-manager (LetsEncrypt SSL certificates). You need to use it in order
   # to fix fails http01 challenges of "cert-manager" (https://cert-manager.io/docs/).
   # Here (https://github.com/compumike/hairpin-proxy) you can find a description of this problem.
   # To be short: the easiest fix provided by some providers (including Hetzner) is to configure the load balancer so
   # that it uses a hostname instead of an IP.
   load-balancer.hetzner.cloud/uses-proxyprotocol: 'true'

   # 1. "yourDomain.com" must be configured in the DNS correctly to point to the Nginx load balancer,
   # otherwise the provision of certificates won't work;
   # 2. if you use a few domains, specify any one.
   load-balancer.hetzner.cloud/hostname: $RANCHER_HOSTNAME
   # [ END: If you care about seeing the actual IP of the client then use these two annotations ]

   load-balancer.hetzner.cloud/http-redirect-https: 'false'
